# Generated by Django 5.1.7 on 2025-03-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorShortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem_statement', models.TextField()),
                ('solution_approach', models.TextField()),
                ('business_model', models.TextField()),
                ('market_audience', models.TextField()),
                ('funding_required', models.CharField(max_length=50)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('pitch_video_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('AI', 'Technology & AI'), ('Healthcare', 'Healthcare & Biotech'), ('Fintech', 'Fintech & Blockchain'), ('EdTech', 'EdTech & E-Learning'), ('SaaS', 'SaaS & Cloud Computing'), ('Ecommerce', 'E-commerce & Retail'), ('SocialImpact', 'Social Impact & Sustainability'), ('ConsumerProducts', 'Consumer Products & Services')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_mentor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyIdeaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_summary', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
