# Generated by Django 5.1.7 on 2025-03-24 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor_dashboard', '0001_initial'),
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investorpitchrequest',
            name='investor',
            field=models.ForeignKey(limit_choices_to={'role': 'INVESTOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investorpitchrequest',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startup'),
        ),
        migrations.AddField(
            model_name='investorshortlist',
            name='investor',
            field=models.ForeignKey(limit_choices_to={'role': 'INVESTOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investorshortlist',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startup'),
        ),
    ]
